# Generated by Django 4.1.7 on 2023-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcl',
            name='description',
        ),
        migrations.AddField(
            model_name='productcl',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
